# Generated by Django 5.2 on 2025-05-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
