# Generated by Django 5.2 on 2025-05-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_alter_passwords_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
